apiVersion: apps/v1
kind: Deployment
metadata:
  name: amiyabot-custom-pools-server
  labels:
    app: amiyabot-custom-pools-server
  namespace: amiya-bot 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amiyabot-custom-pools-server
  template:
    metadata:
      labels:
        app: amiyabot-custom-pools-server
    spec:
      containers:
        - name: amiyabot-custom-pools-server
          image: harbor.hsyhhssyy.net/home-esxi/amiyabot-custom-pools-server:1
          ports:
            - containerPort: 80
          env:
            - name: SQLITE_DB_PATH
              value: "/app/data/db.sqlite3"
          volumeMounts:
            - name: sqlite-data
              mountPath: /app/data

      volumes:
        - name: sqlite-data
          emptyDir: {}
