apiVersion: apps/v1
kind: Deployment
metadata:
  name: amiyabot-custom-pools-server
  labels:
    app: amiyabot-custom-pools-server
  namespace: amiya-bot 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amiyabot-custom-pools-server
  template:
    metadata:
      labels:
        app: amiyabot-custom-pools-server
    spec:
      containers:
        - name: amiyabot-custom-pools-server
          image: harbor.hsyhhssyy.net/home-esxi/amiyabot-custom-pools-server:1
          ports:
            - containerPort: 80
          env:
            - name: SQLITE_DB_PATH
              value: "/app/data/db.sqlite3"
          volumeMounts:
            - name: sqlite-data
              mountPath: /app/data

      volumes:
        - name: sqlite-data
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: amiyabot-custom-pools-server-service
  namespace: amiya-bot
spec:
  selector:
    app: amiyabot-custom-pools-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amiyabot-custom-pools-server-ingress
  namespace: amiya-bot
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - custom-pools-server.hsyhhssyy.net
      secretName: custom-pools-server.hsyhhssyy.net.tls
  rules:
    - host: custom-pools-server.hsyhhssyy.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: amiyabot-custom-pools-server-service
                port:
                  number: 80
